### PR TITLE
Visitos improvements

### LINKED ISSUE #1267: Visitors improvements
By default I get all nebula functions enabled and nebula is not able to update nebula visitors data, so I check nebula visitors and I found somethings are causing problems and some improvements we could add:

1 - We are checking create tables in get_header hook that never if triggered in admin so I move this to admin_init hook

2 - As improvement I update all functions to use a new table names (basically ones using wp db prefix and filtered to allow external modifications)

But I got a ton of errors coming from null inserts:
```
WordPress database error: [Unknown column 'last_session_id' in 'field list']
SELECT last_session_id FROM wp_nebula_visitors WHERE nebula_id = '4.8.12.c6727aed8f.587b617471af2'


Notice: Undefined index: nebula_id in C:\xampp\htdocs\nebula\wp-content\themes\Nebula-master\libs\Utilities\Visitors.php on line 1946

Notice: Undefined index: ga_cid in C:\xampp\htdocs\nebula\wp-content\themes\Nebula-master\libs\Utilities\Visitors.php on line 1947

Notice: Undefined index: ip_address in C:\xampp\htdocs\nebula\wp-content\themes\Nebula-master\libs\Utilities\Visitors.php on line 1948

Notice: Undefined index: user_agent in C:\xampp\htdocs\nebula\wp-content\themes\Nebula-master\libs\Utilities\Visitors.php on line 1949

Notice: Undefined index: fingerprint in C:\xampp\htdocs\nebula\wp-content\themes\Nebula-master\libs\Utilities\Visitors.php on line 1950

Notice: Undefined index: nebula_session_id in C:\xampp\htdocs\nebula\wp-content\themes\Nebula-master\libs\Utilities\Visitors.php on line 1951

Notice: Undefined index: notable_poi in C:\xampp\htdocs\nebula\wp-content\themes\Nebula-master\libs\Utilities\Visitors.php on line 1952

Notice: Undefined index: email_address in C:\xampp\htdocs\nebula\wp-content\themes\Nebula-master\libs\Utilities\Visitors.php on line 1953

Notice: Undefined index: is_known in C:\xampp\htdocs\nebula\wp-content\themes\Nebula-master\libs\Utilities\Visitors.php on line 1954

Notice: Undefined index: last_seen_on in C:\xampp\htdocs\nebula\wp-content\themes\Nebula-master\libs\Utilities\Visitors.php on line 1955

Notice: Undefined index: last_modified_on in C:\xampp\htdocs\nebula\wp-content\themes\Nebula-master\libs\Utilities\Visitors.php on line 1956

Notice: Undefined index: most_identifiable in C:\xampp\htdocs\nebula\wp-content\themes\Nebula-master\libs\Utilities\Visitors.php on line 1957

Notice: Undefined index: lead_score in C:\xampp\htdocs\nebula\wp-content\themes\Nebula-master\libs\Utilities\Visitors.php on line 1958

Notice: Undefined index: notes in C:\xampp\htdocs\nebula\wp-content\themes\Nebula-master\libs\Utilities\Visitors.php on line 1959

Notice: wpdb::prepare was called incorrectly. The query argument of wpdb::prepare() must have a placeholder. Please see Debugging in WordPress for more information. (This message was added in version 3.9.0.) in C:\xampp\htdocs\nebula\wp-includes\functions.php on line 4137
WordPress database error: [Column 'ga_cid' cannot be null]
REPLACE INTO `wp_nebula_visitors` (`nebula_id`, `ga_cid`, `ip_address`, `user_agent`, `fingerprint`, `nebula_session_id`, `notable_poi`, `email_address`, `is_known`, `last_seen_on`, `last_modified_on`, `most_identifiable`, `lead_score`, `notes`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

WordPress database error: [Cannot add or update a child row: a foreign key constraint fails (`nebula`.`wp_nebula_visitors_data`, CONSTRAINT `fk_nebula_visitors_nebula_id` FOREIGN KEY (`nebula_id`) REFERENCES `wp_nebula_visitors` (`nebula_id`) ON DELETE CASCADE)]
INSERT IGNORE INTO wp_nebula_visitors_data (nebula_id, label, value) VALUES ('4.6.14.csd47a565d.58734e3271af2','first_session','0');
```

Apache Server
Os: Win10 (XAMPP)
PHP7

I will report everything

### PR DESCRIPTION
**Pull request by rubengc**
Fixes #1267

### CODE REVIEW

**Comment by chrisblakley** [comment]
I have some edits for this, but I'm having a hell of a time trying to clone the branch of your fork. I'm certain I'm doing something wrong...

```
git clone https://github.com/rubengc/Nebula.git
git checkout visitors-improvements
```

Am I skipping a step or something? The clone works and downloads the master locally, but I don't see either of the branches in my local folder, nor can I change the branch.

**Comment by rubengc** [comment]
I am using github desktop

I forked nebula as usual and currently I am managing 2 branches

**Comment by rubengc** [comment]
Reference to nebula hook issue #1244

**Comment by rubengc** [comment]
I do not have more changes to this PR, we only need to find why errors from #1267 happens

**Comment by chrisblakley** [comment]
I got my local repo figured out. For some reason I had to `cd` after cloning (never had to do it that way before). I'll make a push tonight or tomorrow with some adjustments- I'm running into a bunch of DB errors at the moment.

**Pull request merged**
