### PR TITLE
Options improvements

### PR DESCRIPTION
**Pull request by rubengc**
Current improvements:

More easy to check options enabled/disabled
Nebula options size reduction (now stores '1' instead of 'enabled')

### CODE REVIEW

**Comment by rubengc** [comment]
Screenshot comparing them:
new-options

**Comment by rubengc** [comment]
If we change enable/disable options to 1/0 we got some imrpovements like:

1 - Reduction of nebula options size
2 - More easy to check (1 as int and string means true in conditionals and 0 or empty means false)

**Comment by rubengc** [comment]
New look! you are right about radios will look better
options-as-radio

**Comment by rubengc** [comment]
Oh I keep values 1 for enable, 0 for disable, if you are ok with this change options check like `if( nebula()->option('scss', 'enabled') )` should be `if( nebula()->option('scss', false) )`

and `option()` should be rewritten too (and if you want we could change to `get_option()` too)

**Comment by rubengc** [comment]
Opps a note for this afternoon

Update js to toggle aviability when prototype_mode changes

**Comment by rubengc** [comment]
Check latest commit with hooks a let me know if you like them

I want to add subsections hooks like at analitycs tab, in conversion data section add two actions like:

```php
                        <tr valign="top">
                            <td colspan="2" style="padding-left: 0; padding-right: 0;">
                                <h3>Conversion Data</h3>
                            </td>
                        </tr>

                        <?php do_action( 'nebula_options_analytics_conversion_data_before' ); ?>

                        <tr class="short" valign="top">
                            <th scope="row">&raquo; Event Intent&nbsp;<a class="help" href="#" tabindex="-1"><i class="fa fa-question-circle"></i></a></th>
                            <td>
                                <input class="dimension" type="text" name="nebula_options[cd_eventintent]" value="<?php echo $nebula_options['cd_eventintent']; ?>" />
                                <p class="helper"><small>Log whether the event was true, or just a possible intention. <strong>Scope: Hit</strong><br /><em>&raquo; This dimension is strongly recommended.</em></small></p>
                            </td>
                        </tr>

                        <tr class="short" valign="top">
                            <th scope="row">&raquo; Contact Method&nbsp;<a class="help" href="#" tabindex="-1"><i class="fa fa-question-circle"></i></a></th>
                            <td>
                                <input class="dimension" type="text" name="nebula_options[cd_contactmethod]" value="<?php echo $nebula_options['cd_contactmethod']; ?>" />
                                <p class="helper"><small>If the user triggers a contact event, the method of contact is stored here. <strong>Scope: Session</strong><br /><em>&raquo; This dimension is strongly recommended.</em></small></p>
                            </td>
                        </tr>

                        <tr class="short" valign="top">
                            <th scope="row">Form Timing&nbsp;<a class="help" href="#" tabindex="-1"><i class="fa fa-question-circle"></i></a></th>
                            <td>
                                <input class="dimension" type="text" name="nebula_options[cd_formtiming]" value="<?php echo $nebula_options['cd_formtiming']; ?>" />
                                <p class="helper"><small>Timings are automatically sent to Google Analytics in Nebula, but are sampled in the User Timings report, so they can also be sent along with the each form submission as a Custom Dimension here. Data will be in milliseconds. <strong>Scope: Hit</strong></small></p>
                            </td>
                        </tr>

                        <tr class="short" valign="top">
                            <th scope="row">Video Watcher&nbsp;<a class="help" href="#" tabindex="-1"><i class="fa fa-question-circle"></i></a></th>
                            <td>
                                <input class="dimension" type="text" name="nebula_options[cd_videowatcher]" value="<?php echo $nebula_options['cd_videowatcher']; ?>" />
                                <p class="helper"><small>Sets a dimension when videos are started and finished. <strong>Scope: Session</strong></small></p>
                            </td>
                        </tr>

                        <?php do_action( 'nebula_options_analytics_conversion_data_after' ); ?>
```

Look that I did not added ecommerce cart and customer because this should be added from Ecommerce class

Let me know If you are ok with this and I will update the options class with this hooks too

**Comment by rubengc** [comment]
Reference to nebula options hooks issue #1244

**Comment by chrisblakley** [comment]
I haven't cloned this one yet, but I'll get to it later this week. One thing I'll want to make sure of is that there is enough horizontal space between the radio buttons to avoid confusion.

I definitely like the idea of hooks here, too.

**Comment by chrisblakley** [comment]
I've been wanting to redesign the options page for a little while, too. I wonder if we tackle that here, or get this merged first then redesign it?

**Comment by rubengc** [comment]
Do you want to use a options framework?

The guys from edd use an array of settings that will be turned into html, this array is filtered, so you can add new settings/sections with only one hook

We can follow this idea (an array of settings) that will be turned into html, but I recommend use an existing one (or options framework or a form generator)

I think if nebula offers a built-in form generator (ACF, CMB2 or something one) will be really useful

I am using CMB2 for both, metaboxes forms and options forms and also I created some fields for this one

**Comment by rubengc** [comment]
Oh about merging this, do what you prefer

To turn selects into radios I use a replace all editor function

If we will completely rewrite the options page (for example a hooked array of options fields) then this PR has not sense

**Comment by chrisblakley** [comment]
I'm going to leave this PR here for a bit while we discuss overhauling the Nebula Options page.

I'm not sold on using a framework/plugin for it, though- I'd like to have complete control over everything (frontend/backend) and I want to be able to keep the options and data completely separate.

I'm going to keep poking around for some other examples of good options pages and then eventually I'll start mocking up a design that will allow us to do everything we need. I'll post that stuff over in the issues as it moves.

**Pull request closed without merging**
