### PR TITLE
Customizer improvements

### PR DESCRIPTION
**Pull request by rubengc**
Custom logo support
Site title and description at header bar (needs styling)
Added options to disable/enable hero header in front page
Custom h1 and h2 text in hero header
Possibility to hide search input in hero header
Option to change logo at footer
Possibility to hide search input in footer page

Almost all elements of nebula are covered in customizer with this changes

### CODE REVIEW

**Comment by rubengc** [comment]
Do not merge, I will add css for new titles in header bar

#1201 to automatically close on merge

**Comment by rubengc** [comment]
PD: I not uploaded the compiled css because sure you want to make some changes

**Comment by rubengc** [comment]
I tried to make a new branch to PR in another one but it is PRing to my fork :S

**Comment by chrisblakley** [comment]
Thanks for this- I've got your latest PR partially implemented on my dev server now. This weekend I'm going to try to launch the new documentation site and bring over some nice visual updates to the Nebula theme. Once that's done we can update the Customizer to finish it's implementation.

The only thing I probably won't bite on is the logo with text/subtitle, but everything else is cool. As a note, the new Nebula footer isn't going to have a search field or logo by default, so we can leave/change the Customizer default setting as needed there. Maybe we can put a space for a logo above the power navigation.

**Comment by rubengc** [comment]
I do this logo + title + description settings because this could solve most common setups in this zone

If you like i could change the behavior to keep visible the PickneyHugoGroup logo when user installs the theme at first time, instead to check a box to hide the title or description, make this show them, so at start how user do not have a logo, and this options are not checked, the default logo will be visible

really do not you want keep this feature?

**Comment by chrisblakley** [comment]
Maybe by default the PHG logo is shown and if the user chooses to replace it the whole thing gets swapped out for either the user's image, or we do want to include text I just want to make sure the symbol is also replaced.

Something like this is what I'm thinking:

Default:

nebula-phg

User replaced with their own logo:

nebula-custom-logo

User replaced with text:

nebula-custom-text

**Comment by rubengc** [comment]
Ah, no no, the symbol you see is because I used this symbol as logo but I can set up anything:
captura
captura2
captura3

**Comment by rubengc** [comment]
The screenshots are set in different positions, really the logo or text always are at left (not each one in different positions)

**Comment by chrisblakley** [comment]
Ah ok, sorry for the confusion- I'm good with that.

**Comment by rubengc** [comment]
And now, if everything is hidden and no logo exists, then shows the default logo you want :)

**Comment by chrisblakley** [comment]
Great- I'm going to hold off merging this just so I can push a big update to master and that'll give you a chance to verify if any slight alterations are needed and then we can merge this PR. Admittedly I'm not the greatest with Github merging, so I'm just afraid of something important getting overwritten.

**Comment by rubengc** [comment]
I PR latest commit of customizer (with footer text) on third party support PR :/

Add this lines to the footer (replaces line 25) to make new customizer option work, also, could print html (for &copy; and b and em tags)

```php
							<?php if ( ! empty( get_theme_mod('nebula_footer_text', '') ) ): ?>
								<span><?php echo html_entity_decode( get_theme_mod('nebula_footer_text', '') ); ?></span>
							<?php endif; ?>
```

**Comment by rubengc** [comment]
This PR needs something?

**Comment by chrisblakley** [comment]
I pushed a couple big updates since this PR, so conflicts just need to be resolved. I'm also scratching my head trying to figure out a way to allow footer search by default without requiring my devs to use the Customizer.

**Comment by rubengc** [comment]
Do you want to keep the footer logo?

Currently if you set a footer logo footer menu widths is not correctly set, I suppose footer logo should be inside `copyright` container instead of `powerfootercon`

**Comment by rubengc** [comment]
Footer search is enabled by default, option in customizer is to hide it

```php
if ( ! get_theme_mod( 'nebula_hide_footer_search', false) ) // ! false by default
```

**Comment by chrisblakley** [comment]
I'm running into issues again with the Customizer. I like the idea of it, but I keep running into problems. Is there no way to reset the colors?

If I set a color using the Customizer, everything updates to that color, which is great. But then if (for whatever reason) I want to reset the Customizer so that my Sass colors are used again, I'll click "Default" in the Customizer and re-save, but now it still pulls the Customizer color- just the default one instead of falling back to the Sass color.

It seems that once the Customizer is used once, it can't *not* be used thereafter. Like, `get_theme_mod()` will never fall back to the 2nd parameter...

I see plugins that claim to truly be able to reset the Customizer, but I don't want to install a plugin just for the purpose.

Any thoughts on this? Maybe I'm doing something wrong (as I'm still new to the Customizer)?

**Comment by rubengc** [comment]
I test it and I can confirm the issue, I do not know how to solve this but I will try to contact a theme developer for sure knows why this happen

Anyway this PR has something new? I think nebula oop PR has all this changes, so you can discard this PR and we could keep this as an issue

**Comment by rubengc** [comment]
If you are ok to move this into a issue will be awesome, because I am not able to update my master branch (I will re-fork this repo)

**Comment by chrisblakley** [comment]
Ok, will close this PR and move it into a new issue.

**Pull request closed without merging**
