### PR TITLE
Nebula OOP

### LINKED ISSUE #1169: Would having a nebula class have significant benefits?
Would creating a `Nebula` class with its functions have significant benefits over the procedural way it's done now? I _feel_ like it's the right way to do it, but I just haven't been convinced that the benefits would be measurable...

``` php
class nebula {
    public function is_dev(){
        return true;
    }

    public function is_chris_cool(){
        return true;
    }

    public function add_numbers($a, $b){
        return $a+$b;
    }
}

$nebula = new nebula();
$nebula->is_dev();
$nebula->add_numbers(2, 6);
```

### PR DESCRIPTION
**Pull request by rubengc**
Fixes #1169

To test it clear functions.php and add:
```php
require_once('nebula.php');

nebula();
```

Currently I only receive a blank screen, sure some function from old files

### CODE REVIEW

**Comment by chrisblakley** [comment]
I did some digging on the white screen issue.

- Undefined function nebula_manifest_json_location() in header.php (Line 26)
- Undefined function nebula_prerender() in header.php (Line 28)

Adding this to functions.php fixes it:
```php
function nebula_manifest_json_location(){
    return nebula()->functions->manifest_json_location();
}

function nebula_prerender(){
    return nebula()->functions->prerender();
}
```

That'll get us out of the white screen error. Also seeing this:

- Undefined function footerWidgetCounter() in footer_widgets.php (Line 9)

Which is fixed by updating the template file to the correct syntax (which you have already corrected in the OOP file):

```php
footer_widget_counter();
```

**Comment by chrisblakley** [comment]
I'm thinking we move all of the "alias" functions (the ones that now just call the OOP counterpart) into legacy.php in the functions file.

Eventually we'll aim to remove them completely, but that'll be the first step to organize things better.

**Comment by rubengc** [comment]
On templates we should not use OOP functions to meet WordPress standard

If some functions do not have sense to keep in class we can move out 

I passed a lot of functions to OOP so I do not revise each one in deep

Today I will countinue with options and utilities

**Comment by rubengc** [comment]
Options and user fields done!

Next prototyping and the big last one, utilities!

**Comment by rubengc** [comment]
Prototyping and utilities done!

I will commit everything this afternoon

**Comment by rubengc** [comment]
Check this changes!

The refactoring will be more stronger but is a nice opportunity to revise everything and make changes needly to get a better nebula

let me know what you decide about template functions (to me, their should maintian wordpress standard)

**Comment by chrisblakley** [comment]
I think I like the subdivision of files like you have in the /functions/admin directory, so that's cool. I only took a really quick glance, but it appears there is a mysterious `<strong>` tag appearing on the WP Admin Dashboard that is wrapping metaboxes making everything bold. Couldn't look any further into it, but I wanted to note it.

Regarding the template files, I'll trust your judgement until I can get my hands dirty with the OOP backend code a bit more, so we can leave them. Is it typical of OOP themes to have alias functions like that? Seems like a hybrid between procedural and OOP.

What do you think about adding a "procedural" or even "legacy" directory for the old nebula_*.php files? I'd like to keep them around for a little bit even after I merge (just for reference) and then eventually we can trash them.

**Comment by rubengc** [comment]
I separate sass methods into a sass class

I move all template functions into template-functions.php

I will search this strong tag yo fix it

I like the idea of keep a legacy directory until we are migrating everything and while we check all functionalities

**Comment by rubengc** [comment]
Old files moved to legacy folder

New class Nebula_Google_Analytics

**Comment by rubengc** [comment]
I fixed a lot of lines with current structure

But some parts fails (normally is a "method does not exists")

I will commit all changes as soon as possible

**Comment by chrisblakley** [comment]
Ok, I got the frontend working along with some Dashboard fixes on your OOP branch. For the time-being, I just used the OOP method calls directly from the template files- we can make aliases as needed if you think we should change that.

**Comment by rubengc** [comment]
Todo: recover some missing template functions (nebula_breadcrumb is one I found)

**Comment by rubengc** [comment]
with latest changes, I have a full working nebula instance

Check what you need to marge it

**Comment by chrisblakley** [comment]
I'm going to be pushing some major updates to the Visitor DB (nebula_utilities.php and nebula_admin.php), so it might take a bit to resolve merge conflicts.

**Comment by chrisblakley** [comment]
I just pushed the first major update to a few backend files, so this PR is going to have some large conflicts now.

**Comment by rubengc** [comment]
I will work on this to take this finished today

**Comment by rubengc** [comment]
To check:
options
security
utilities

**Comment by rubengc** [comment]
Only I need update nebula sass functions and this PR will be ready

**Comment by rubengc** [comment]
I checked all files from latest commit, we will need test it a bit but now is up to date to be merged

**Comment by rubengc** [comment]
Hey @chrisblakley 

Can you review this changes as soon as posible? I have some new features I want to show you :)

**Comment by chrisblakley** [comment]
Yeah- I just keep making commits to function files, but I think I'm at a point where I'm done making modifications. I'm going to push one more commit to master and then we can start merging the OOP stuff.

**Comment by rubengc** [comment]
Nice!

Let me know when you have ready this last commit and I will update (again) al functions of each class

**Comment by chrisblakley** [comment]
Just pushed the commit- I'll hold off on any other changes until we get this OOP update merged.

**Comment by chrisblakley** [comment]
Ok, I updated the branch on your fork to fix a bunch of conflicts and fatal errors as well as update it to match the directory structure so we're one more step closer.

**Comment by chrisblakley** [comment]
I've been playing around with this a bit this weekend to try to get used to it, and I have a few edits I want to make.

The main big thing I'm not a huge fan of is the prefixed alias functions (basically procedural inside of OOP). I don't mind calling the OOP functions directly in template files- especially since it would help separate the Nebula functions from core WP (or other plugin) functions. However, I don't want to require Nebula devs to know where each function is defined. So, while I like the new organization of files in the `/libs` directory, ideally we'd be able to call all Nebula methods directly from the top-level `nebula()` function.

For example:
I want to avoid this:
```
<meta class="theme-color" name="theme-color" content="<?php echo nebula_sass_color('primary'); ?>">
```

I want to avoid this:
```
<meta class="theme-color" name="theme-color" content="<?php echo nebula()->utilities->sass->sass_color('primary'); ?>">
```

I'd like to do this (without changing our directory structure in `/libs`:
```
<meta class="theme-color" name="theme-color" content="<?php echo nebula()->sass_color('primary'); ?>">
```

**Comment by rubengc** [comment]
Keep in mind traits are not possible to instantiate so contructor hooks will not work

If we instantiate Nebula_Sass inside nebula we can get this result `nebula()->sass->color('primary');` for `nebula()->sass_color('primary');`

To me, we should move GA, Visitors, device detection and sass inside nebula and turn Nebula_Utilities into a trait (`fuzzy_posts_where` should go in Nebula_Functions)

Currently Nebula_Utilities is a container of useful functions so this class is a great candidate to become a trait, What do you think?

**Comment by chrisblakley** [comment]
I modified the version on my server to use traits instead of classes and while it worked I'm getting Maximum execution time errors out the wazoo.

Have any ideas of how we could work without a constructor? I mean, we would still get one in the main Nebula class, so one choice would be to use all hooks there (just thinking out loud). Ideally we'd keep the hooks within their individual files- could we just run a function immediately when the trait is called and throw the hooks in that?

I've still got a procedural mentality, so there might be ideas that I'm not thinking about.

I do love the way traits allow organizing the functions/methods while providing simplicity to the template files, so I do want to continue down this path. If you want, I'll push what I've done to your fork, but I'm certain it's bloated right now so if you want to put the wheels in motion that's fine too- just let me know. In the meantime, I'm going to continue playing around.

**Comment by rubengc** [comment]
Nice, commit you version to let me test

I have been reading about traits performance, apparently they do not have any negative effect (Include, I read comments about how to slightly improved the execution speed), so probably your max execution time errors come from hooks registered many times

About register hooks without constructor, they are in constructors trying to avoid multiple hook registration being instantiated inside a singleton class (Nebula)

If you have hooks inside a method, this needs to be public (to be accesible from wp-hook) and this opens the door to being called again (intentionally or by a mistake)

A class/file can contain a lot of useful functionalities without get any wordpress reference inside, for example, Nebula_Sass can handle everything related to sass files manipulation but hooks to automatically compile sass files can come inside Nebula_Functions

**Comment by chrisblakley** [comment]
Ok, cool- good thoughts. I'll play around with this a little more tonight and push a commit to your fork because I was pretty hack and slash about it. There are some blanket comments that I'll need to put back in first.

**Comment by rubengc** [comment]
I see you are turning some strong classes with a couple of hooks as traits, are you sure about this?

If you want to keep this way we need to move constructor hooks into the class that will use them (for example, move admin dashboard hooks into admin)

**Comment by rubengc** [comment]
After run current version without any php errors I get this:

Fatal error: Allowed memory size of 551550976 bytes exhausted (tried to allocate 262144 bytes) in C:\xampp\htdocs\nebula\wp-includes\cache.php on line 548

Fatal error: Allowed memory size of 551550976 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0

From `Unknown` ...

**Comment by chrisblakley** [comment]
Yeah that's what I was seeing as well. I'm thinking you may be on the right track when you were thinking either a hook or function is being called many times (possibly recursively)...

**Comment by rubengc** [comment]
I am debugging it, and apparently an infinite loops of get options happens in nebula-master/header.php

I am investigating why

**Comment by rubengc** [comment]
Oh, to reduce the search, is a hook inside wp_head()

**Comment by chrisblakley** [comment]
I confirmed what you found that it was definitely something in the `wp_head()` hook. I've narrowed it down to being inside `/libs/scripts.php`. I'll update as I find more info.

**Comment by chrisblakley** [comment]
Are traits scoped to the class that uses it? Like, if we didn't prefix our traits, would we run into conflicts if a plugin somewhere also had a trait named `Shortcodes`?

I'm playing with using an autoloader instead of needing to `require_once` all of the files. In doing so, I'd like to un-prefix the trait names and possibly introduce a namespace. I'm curious about your thoughts on that.

Here's what I was thinking:
```php
spl_autoload_register(function($name){
	$filepath = get_template_directory() . '/libs/' . str_replace(array('\\', 'nebula_', '_'), array('/', '', '-'), strtolower($name)) . '.php';
	require_once $filepath;
});
```

```php
use Nebula_Template_Engine;
use Nebula_Scripts;
use Nebula_Options;
use Utilities\Nebula_Utilities;
use Nebula_Security;
use Nebula_Optimization;
use Nebula_Functions;
use Nebula_Shortcodes;
```

I'm having difficulty with the traits that are nested within subdirectories (Utilities and Admin)...

**Comment by rubengc** [comment]
I think we should keep a prefix in each trait to avoid any conflicts and we need to encapsule It in a `trait_exists` check

I am not fan of autoloaders, precisely I reported some days ago a problem coming from a duplicated declaration of an autoloader class (basically the autoloader is preventing duplicate loaded classes but not itself declaration)

**Comment by chrisblakley** [comment]
I like the idea of removing prefixes if possible across Nebula, but we can do what we need to do. I was toying around with namespacing- I wasn't married to the idea, but if it helps I'm cool with it.

I'm fine going with whatever works, but I figured at this stage we might as well experiment with some ideas.

**Comment by chrisblakley** [comment]
Ok getting really close now. I've got everything working except for the `__construct()` stuff- gonna need some help figuring that out... Besides that I think we're in really good shape.

Once the `__construct()` is working I'll do a thorough pass to make sure the new methods are all named appropriately.

Also, I took the namespaces out (you may have seen it prior to my previous commit). We can add them back in if it helps scope the traits to the Nebula class... otherwise we'd need to prefix the traits again (which I'd really love to avoid). I'd like to keep the file/directory naming structure because it would lend itself to future enhancements that way. I did update everything to a `trait_exists()` now, too.

**Comment by rubengc** [comment]
I added this prefix to classes because I based this on WordPress coding standards and also I am adding spaces before and after of `(` and `)`

https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/

**Comment by rubengc** [comment]
I am checking the code and I only see two possibilities to solve the problem with hooks

1 - Move all hooks inside `nebula()->hooks()` function, something that will turn hooks function into a "impossible to read" hooks container

2- Make a `hooks()` or `register_hooks()` function in each trait and we need to set up Nebula class as:
```php

....

    class Nebula {
		use TemplateEngine { hooks as TemplateEngineHooks };
		use Scripts { hooks as ScriptHooks };

....

        private function hooks() {
            //Start a session
            add_action('init', array( $this, 'session_start' ), 1);

            //Adjust the content width when the full width page template is being used
            add_action('template_redirect', array( $this, 'set_content_width' ) );

            $this->TemplateEngineHooks(); // Register TemplateEngine hooks
            $this->ScriptHooks(); // Register Script hooks
        }

    }
```

With a trait containing other traits we need to setup the same:
```php

.....

    trait Admin {
		//Only use these on actual admin pages (not also for admin bar)
		use Automation { hooks as AutomationHooks };
		use Dashboard { hooks as DashboardHooks };
		use Users { hooks as UsersHooks };

.....

        public function hooks() {
            //Force expire query transients when posts/pages are saved.
            add_action('save_post', array( $this, 'clear_transients' ) );

            //Disable auto curly quotes (smart quotes)
            remove_filter('the_content', 'wptexturize');
            remove_filter('the_excerpt', 'wptexturize');
            remove_filter('comment_text', 'wptexturize');
            add_filter('run_wptexturize', '__return_false');

            .....

            $this->AutomationHooks();
            $this->DashboardHooks();
            $this->UsersHooks();
        }

            .....

    }
```

I've never worked this way before, so I do not know what can be the most effective way to proceed

**Comment by chrisblakley** [comment]
Ok great thanks for pointing me in the right direction. I've got them all fully working now.

Only issue I'm seeing now is this warning from TemplateEngine.php:
```
Warning: array_reverse() expects parameter 1 to be array, null given in wp-content/themes/Nebula-master/libs/TemplateEngine.php on line 164
```

I looked into it a little bit, but I didn't want to take any guesses and break your functionality.

It's looking like we may be 1 commit away from merging this PR.

**Comment by rubengc** [comment]
Nice!

I will check everything about nebula integrations

Are you ok to setup template and sass needs automatically from register_plugin?

**Comment by chrisblakley** [comment]
> Are you ok to setup template and sass needs automatically from register_plugin?

Can you clarify what you'd need from me on this one? I added filters for Sass directories so that should work for any number of additional plugins working with Nebula already (without needing a separate/duplicate function).

**Comment by rubengc** [comment]
I mean by registering plugin in nebula, If plugin has the properly dir structure (assets/scss/ and templates/) automatically load them inside sass and template engine (remember template engine is rewriting WordPress template system to load theme files from plugins, is based on grandchilds themes workflow)

I want to setup `register_plugin` similar to `register_post_type` with an identifier and an array of args and with some automatic functionalities to allow devs setup easily and quickly a plugin inside the nebula enviroment

Do you like this workflow?

**Comment by chrisblakley** [comment]
I'm fine with registering plugins with Nebula to allow for grandchild theming and other plugin dev- but I'd like to avoid requiring a specific directory structure. While we can "prefer" it to match what we've established, the beauty of the `apply_filter()` hook is that we can basically register Sass locations with *any* directory structure.

What if we modify the  `register_plugin` functionality to take an array of Sass directories and it then adds them using the filter I set up?

Something like this:
```php
add_filter('nebula_scss_locations', 'my_plugin_scss_files');
function my_plugin_scss_files($scss_locations){
    $scss_locations['my_plugin'] = array(
		'directory' => plugin_dir_path(__FILE__),
		'uri' => plugin_dir_url(__FILE__),
		'imports' => plugin_dir_path(__FILE__) . '/scss/partials/'
	);
    return $scss_locations;
}
```

Would that work for you?

**Comment by rubengc** [comment]
Check the new `register_plugin()` it follows wordpress standards

If user only pass second parameter as string with the plugin path, then will check if user has the assets/scss and templates directories to make it work with nebula

If user pass second parameter as array he can define their custom scss and templates directory

I do not want to force to any structure, but if dev meets the same standards as wordpress and current nebula structure he could get his plugins integrated easily

Let me know if you like this new functions and I will update the boilerplate 😄

**Comment by rubengc** [comment]
Oh, I forget on commit talk about a fix in comments.php (call to nebula_option missing function)

**Comment by chrisblakley** [comment]
I think that's a good solution- that's a good way to not force the directory structure while still preferring it by making it easier.

Cool- when I get home tonight (or tomorrow) I'll pull the latest commit and do some final testing on my server and then if it's still all good I'll try to merge it.

**Comment by rubengc** [comment]
Nice! I will update boilerplate and nebula-edd to meet latest nebula version

**Comment by chrisblakley** [comment]
Ok, merged with my repo- still going to be a few days at least for me to get the documentation updated for new file locations/names, but it's now available on Github.

**Pull request merged**
